name: poc_assignment
description: "A Flutter app that displays posts from JSONPlaceholder with filtering, bookmarks, and author names."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
